In [1]:
import pandas as pd
df = pd.read_excel(r"C:\Users\abhis\Downloads\Sales-Data-Analysis.xlsx",header=0)
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,NaN,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,NaN,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,NaN,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,NaN,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin

In [31]:
df.columns = df.iloc[0]
df.head()

,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London,2000.0,2022-11
0,10452,2022-11-07,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London,2000.0,2022-11
1,10453,2022-11-07,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid,2200.0,2022-11
2,10454,2022-11-07,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon,1000.0,2022-11
3,10455,2022-11-08,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin,7400.0,2022-11
4,10456,2022-11-08,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin,2000.0,2022-11

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nan             0 non-null      float64
 1   Order ID        255 non-null    object
 2   Date            255 non-null    object
 3   Product         255 non-null    object
 4   Price           255 non-null    object
 5   Quantity        255 non-null    object
 6   Purchase Type   255 non-null    object
 7   Payment Method  255 non-null    object
 8   Manager         255 non-null    object
 9   City            255 non-null    object
dtypes: float64(1), object(9)
memory usage: 20.0+ KB

In [4]:
#df=df.drop(columns=["unnamed:0"])
#df = df.drop(columns=["NaN"])
df = df.dropna(axis=1, how="all")

In [5]:
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin

In [6]:
df = df[df["Order ID"] != "Order ID"].reset_index(drop=True)

In [7]:
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
1,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
2,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
3,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
4,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin

In [8]:
# df=df[df["Order ID"] < 10455]
# df.head()

In [9]:
# #df=df.drop(columns=["Order ID:1"])
# #df = df.drop(columns=["Order ID"])
# df=df.drop(index=1)
# df.head()

In [10]:
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
1,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
2,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
3,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
4,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin

In [11]:
df["Date"] = pd.to_datetime(df["Date"])
df["Price"] = df["Price"].astype(float)
df["Quantity"] = df["Quantity"].astype(float)
df["Order ID"] = df["Order ID"].astype(int)

In [12]:
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,2022-11-07,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
1,10453,2022-11-07,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
2,10454,2022-11-07,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
3,10455,2022-11-08,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
4,10456,2022-11-08,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin

In [13]:
print("----------------------------------------info-----------------------------------------------")
df.info()
print("----------------------------------------isnasum-----------------------------------------------")
df.isna().sum()
print("----------------------------------------describe-----------------------------------------------")
df.describe()

----------------------------------------info-----------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    int32
 1   Date            254 non-null    datetime64[ns]
 2   Product         254 non-null    object
 3   Price           254 non-null    float64
 4   Quantity        254 non-null    float64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: datetime64[ns](1), float64(2), int32(1), object(5)
memory usage: 17.0+ KB
----------------------------------------isnasum-----------------------------------------------
----------------------------------------describe-----------------------------------------------

0          Order ID                           Date       Price    Quantity
count    254.000000                            254  254.000000  254.000000
mean   10584.133858  2022-12-03 10:23:37.322834688    7.102323  460.610541
min    10452.000000            2022-11-07 00:00:00    2.950000  200.400802
25%    10520.250000            2022-11-21 00:00:00    3.490000  201.005025
50%    10583.500000            2022-12-03 00:00:00    4.990000  538.876059
75%    10649.750000            2022-12-16 18:00:00    9.950000  677.444188
max    10713.000000            2022-12-29 00:00:00   29.050000  754.426482
std       75.889181                            NaN    4.341855  214.889551

In [14]:
df["Revenue"] = df["Price"] * df["Quantity"]
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City,Revenue
0,10452,2022-11-07,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London,2000.0
1,10453,2022-11-07,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid,2200.0
2,10454,2022-11-07,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon,1000.0
3,10455,2022-11-08,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin,7400.0
4,10456,2022-11-08,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin,2000.0

In [15]:
total_revenue = df["Revenue"].sum()
total_orders = df["Order ID"].nunique()
avg_order_value = total_revenue / total_orders
print(f"total revenue :",total_revenue,"\ntotal orders:", total_orders,"\navg value per order:", avg_order_value)

total revenue : 769513.6945472348
total orders: 254
avg value per order: 3029.5814745954126

In [16]:
product_revenue = (
df.groupby("Product")["Revenue"]
.sum()
.sort_values(ascending=False)
)
product_revenue

Product
Burgers               377000.000000
Fries                 125674.498567
Chicken Sandwiches    114639.195980
Beverages             103200.000000
Sides & Other          49000.000000
Name: Revenue, dtype: float64

In [17]:
product_qty_rev = df.groupby("Product")[["Quantity", "Revenue"]].sum()
product_qty_rev

0                       Quantity        Revenue
Product
Beverages           34983.050847  103200.000000
Burgers             29022.324865  377000.000000
Chicken Sandwiches  11135.678392  114639.195980
Fries               32034.383954  125674.498567
Sides & Other        9819.639279   49000.000000

In [18]:
# product_quantity_rev=df.groupby("Product")[["Quantity","Revenue"]].sum()

In [19]:
purchase_type_rev = df.groupby("Purchase Type")["Revenue"].sum()
purchase_type_rev

Purchase Type
Drive-thru     178600.000000
In-store       285713.694547
Online         305200.000000
Name: Revenue, dtype: float64

In [20]:
purchase_type_rev = df.groupby("Purchase Type")["Revenue"].sum().sort_values(ascending=False)
purchase_type_rev

Purchase Type
Online         305200.000000
In-store       285713.694547
Drive-thru     178600.000000
Name: Revenue, dtype: float64

In [21]:
product_channel = pd.pivot_table(
df,
values="Revenue",
index="Product",
columns="Purchase Type",
aggfunc="sum"
)
product_channel

Purchase Type       Drive-thru       In-store    Online
Product
Beverages               25200.0   32800.000000   45200.0
Burgers                 88400.0  140600.000000  148000.0
Chicken Sandwiches      27800.0   43839.195980   43000.0
Fries                   25200.0   52474.498567   48000.0
Sides & Other           12000.0   16000.000000   21000.0

In [22]:
manager_revenue = (
df.groupby("Manager")["Revenue"]
.sum()
.sort_values(ascending=False)
)
manager_revenue

Manager
Joao Silva            225074.498567
Tom Jackson           209200.000000
Pablo Perez           107600.000000
Walter Muller         100600.000000
Remy Monet             72800.000000
       Pablo Perez     23200.000000
Joao    Silva          16639.195980
       Remy Monet       4000.000000
Pablo   Perez           2200.000000
Pablo  Perez            2200.000000
Remy    Monet           2000.000000
Tom      Jackson        2000.000000
Pablo    Perez          1000.000000
Remy     Monet          1000.000000
Name: Revenue, dtype: float64

In [23]:
city_revenue = (
df.groupby("City")["Revenue"]
.sum()
.sort_values(ascending=False)
)
city_revenue

City
Lisbon    241713.694547
London    211200.000000
Madrid    136200.000000
Berlin    100600.000000
Paris      79800.000000
Name: Revenue, dtype: float64

In [24]:
df["Month"] = df["Date"].dt.to_period("M")
monthly_revenue = df.groupby("Month")["Revenue"].sum()
monthly_revenue

Month
2022-11    332113.694547
2022-12    437400.000000
Freq: M, Name: Revenue, dtype: float64

In [25]:
high_qty_orders = df[df["Quantity"] > df["Quantity"].quantile(0.99)]
high_qty_orders

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City,Revenue,Month
250,10710,2022-12-29,Burgers,12.99,754.426482,Drive-thru,Gift Card,Walter Muller,Berlin,9800.0,2022-12

In [26]:
product_revenue.to_csv("product_revenue.csv")
product_channel.to_csv("product_channel.csv")
manager_revenue.to_csv("manager_revenue.csv")
city_revenue.to_csv("city_revenue.csv")
monthly_revenue.to_csv("monthly_revenue.csv")

In [27]:
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City,Revenue,Month
0,10452,2022-11-07,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London,2000.0,2022-11
1,10453,2022-11-07,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid,2200.0,2022-11
2,10454,2022-11-07,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon,1000.0,2022-11
3,10455,2022-11-08,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin,7400.0,2022-11
4,10456,2022-11-08,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin,2000.0,2022-11

In [28]:
df

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City,Revenue,Month
0,10452,2022-11-07,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London,2000.0,2022-11
1,10453,2022-11-07,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid,2200.0,2022-11
2,10454,2022-11-07,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon,1000.0,2022-11
3,10455,2022-11-08,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin,7400.0,2022-11
4,10456,2022-11-08,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin,2000.0,2022-11
...,...,...,...,...,...,...,...,...,...,...,...
249,10709,2022-12-28,Sides & Other,4.99,200.400802,Drive-thru,Gift Card,Walter Muller,Berlin,1000.0,2022-12
250,10710,2022-12-29,Burgers,12.99,754.426482,Drive-thru,Gift Card,Walter Muller,Berlin,9800.0,2022-12
251,10711,2022-12-29,Chicken Sandwiches,9.95,281.407035,Drive-thru,Gift Card,Walter Muller,Berlin,2800.0,2022-12
252,10712,2022-12-29,Fries,3.49,630.372493,Drive-thru,Gift Card,Walter Muller,Berlin,2200.0,2022-12
253,10713,2022-12-29,Beverages,2.95,677.966102,Drive-thru,Gift Card,Walter Muller,Berlin,2000.0,2022-12